apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: contract-golden-image-on-push
  annotations:
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: '[push]'
    pipelinesascode.tekton.dev/on-target-branch: '[main]'
spec:
  params:
    - name: git-url
      value: '{{repo_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: 'quay.io/redhat-appstudio/ec-golden-image:{{revision}}'
    - name: dockerfile
      value: ./Containerfile
    - name: path-context
      value: .
    - name: hermetic
      value: 'true'
    - name: snyk-secret
      value: snyk-shared-secret
  pipelineRef:
    resolver: bundles
    params:
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/pipeline-docker-build:devel@sha256:48841b87d60e855f50c92ad142d1ec374191c443c32008c3476e209a892f1b60
      - name: name
        value: docker-build
      - name: kind
        value: pipeline
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
